### ISSUE TITLE
Atom Editor 1.6 i686 isn't starting properly

### ISSUE THREAD

**Issue by rafaelsoaresbr** [sjug/atom-editor#4]
![screenshot at 2016-03-27 23 52 28](https://cloud.githubusercontent.com/assets/13059863/14070755/97659622-f478-11e5-9766-829623646595.png)

After updating from 1.5 to 1.6, Atom isn't starting properly. Any hints?

**Comment by rafaelsoaresbr** [comment]
This Issue is reported upstream
https://github.com/atom/atom/issues/10819

**Comment by sjug** [comment]
Hey @rafaelsoaresbr, thanks for the heads up. We can keep this issue open and I'll keep updating the AUR package as upstream rolls out the fixes.

Also if there's a patch released before it's merged we can also put that into the package.

**Comment by rafaelsoaresbr** [comment]
@sjug Version 1.6.2 will build and run successfully on Arch Linux i686 after this pull request (merged):
https://github.com/nodegit/nodegit/pull/980

I've edited packages.json (inside source tar ball) on line #40:

```
"nodegit": "0.12.0",  -> "nodegit": "0.12.2", 
```

Can you make a patch for it? Or just include a condition in you PKGBUILD's prepare() fase until next release of Atom:

```
if [[ "$CARCH" == "i686" ]]; then
    --some useful code here--
fi
```

This should do the trick for others distros as well:
https://github.com/atom/atom/issues/10819
https://github.com/nodegit/nodegit/issues/974

Future versions may build and run as well after this pull request (yet to be merged):
https://github.com/atom/atom/pull/11401

Thanks @johnhaley81 @tbranyen and @SEAPUNK

**Comment by sjug** [comment]
Hey Rafa,

This is still an issue on 1.7.0?

**Comment by sjug** [comment]
Fixed, please let me know if it works! https://github.com/sjug/atom-editor/commit/276db3d0b4e88103bd7121d672f00c18bdd16ca4

**Comment by rafaelsoaresbr** [comment]
Thanks, I'm building it right now.

**Comment by SEAPUNK** [comment]
Same. Will let you know if it's fixed on my end.

**Comment by SEAPUNK** [comment]
It works, thanks.

**Comment by roshimon** [comment]
Upgrading to atom 1.8.0-beta1 has fixed the issue for me. Working flawlessly now :)
